AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the sam-practice-service
Globals:
  Function:
    Runtime: python3.9
    Timeout: 3
    MemorySize: 128
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.hello
      FunctionName:
        Fn::Sub: ${StackBaseName}-${Stage}
      LoggingConfig:
        LogGroup:
          Fn::Sub: /aws/lambda/${Service}-${Stage}-hello
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-bq1tk4lo0ar5/sam-practice-service-dev/6e7ae8f95487f52b6040511fb045de82
    Metadata:
      SamResourceId: HelloFunction
  HelloLog:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: 
        Fn::Sub: /aws/lambda/${Service}-${Stage}-hello
Parameters:
  Stage:
    Type: String
    Default: dev
  StackBaseName:
    Type: String
    Default: sam-practice-service
  Service:
    Type: String
    Default: serverless-practice-service
Outputs:
  HelloFunction:
    Description: Hello Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloFunction
      - Arn
