version = 0.1

[default.build.parameters]
debug = true
use_container = false

[dev.deploy.parameters]
debug = true
confirm_changeset = true
disable_rollback = false
resolve_s3 = true
region = "ap-northeast-1"
s3_prefix = "sam-practice-service-dev"
stack_name = "sam-practice-service-dev"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"

[stg.deploy.parameters]
debug = true
confirm_changeset = true
disable_rollback = false
resolve_s3 = true
region = "ap-northeast-1"
s3_prefix = "sam-practice-service-stg"
stack_name = "sam-practice-service-stg"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=stg"