AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the sam-practice-service

Globals:
  Function:
    Runtime: python3.9
    Timeout: 3
    MemorySize: 128

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.hello
      FunctionName: !Sub "${StackBaseName}-${Stage}"

  # MyBucket:
  #   Type: AWS::S3::Bucket
  #   DeletionPolicy: Retain
  #   Properties:
  #     BucketName: !Sub '${Service}-${Stage}'
Parameters:
  Stage:
    Type: String
    Default: dev
  StackBaseName:
    Type: String
    Default: sam-practice-s3

  # 移行前のServerless frameworkのスタック名
  Service:
    Type: String
    Default: serverless-practice-s3

Outputs:
  HelloFunction:
    Description: "Hello Lambda Function ARN"
    Value: !GetAtt HelloFunction.Arn

